# Generated by Django 4.1.6 on 2023-02-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplePage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Page',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='views',
            new_name='visits_count',
        ),
    ]
