# Generated by Django 4.1.6 on 2023-02-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samplePage', '0002_rename_post_page_rename_views_page_visits_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Page',
            new_name='Page1',
        ),
    ]
