# Generated by Django 4.1.6 on 2023-02-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplePage', '0003_page2_page3_rename_page_page1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page1',
            old_name='visits_count',
            new_name='visits_count1',
        ),
        migrations.RenameField(
            model_name='page2',
            old_name='visits_count',
            new_name='visits_count2',
        ),
        migrations.RenameField(
            model_name='page3',
            old_name='visits_count',
            new_name='visits_count3',
        ),
    ]
