# Generated by Django 4.1.6 on 2023-02-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplePage', '0006_arithmeticaverage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArithmeticAverage',
        ),
    ]
